Repository palantir/gradle-processors, pull requests merged in 2019-08, with the labels that each got.

#114 Move to templated circleci config
  .circleci/config.yml
  .circleci/template.sh
  .travis.yml
  build.gradle
Labels: no changelog

#116 Fix publishing
  build.gradle
Labels: no changelog

#115 [break] Gradle 46 only
  README.md
  build.gradle
  changelog/@unreleased/pr-117.v2.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/groovy/org/inferred/gradle/ProcessorsPlugin.groovy
  src/test/groovy/org/inferred/gradle/ProcessorsPluginFunctionalTest.groovy
  src/test/groovy/org/inferred/gradle/ProcessorsPluginTest.groovy
Labels: merge when ready

#120 Correctly set project name
  changelog/@unreleased/pr-120.v2.yml
  settings.gradle
Labels: autorelease, merge when ready
